name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-slim
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v6.0.8
        with:
          run_install: false

      - run: pnpm install --frozen-lockfile -P

      - run: pnpm run build

      - run: |
          cd .output/chrome-mv3
          zip -r ../../super-screenshot-chrome-mv3.zip .

      - uses: softprops/action-gh-release@v2
        with:
          files: super-screenshot-chrome-mv3.zip
